### PR TITLE
support for requirejs loader plugins dependencies with relative paths

### PR DESCRIPTION
**Pull request by purtuga**
This is related to issue #75 
Basically: it adds support for loader plugins that have relative path dependencies in them (ex. text!../ui/page.html). I added a test case to demonstrate the issue.
Also: note that when I checked out MASTER, one test case was failing... I fixed that one as well.

### CODE REVIEW

**Comment by aarongloege** [comment]
What is the status on this pull request? I am currently experiencing the issue this pull request would resolve.

**Comment by purtuga** [comment]
Hey Aaron,
If you need to quickly get around this problem and are using a package manager to down/install AMDClean, just use the url to the zip on my fork... something like (`npm` `package.json` example below):

```
"devDependencies": {
    "amdclean": "https://github.com/purtuga/amdclean/archive/d6ccd513c0394b70a023a256aecc4c92375beb8e.zip"
  },
```
I will only delete my fork once Greg has merged in this fix, because I'm also using it... so until then, it should be pretty safe to use. :)

/Paul

**Comment by aarongloege** [comment]
Thanks for the reply Paul.

For now I just forked the repo and merged in your pull request. Fixed my problem. Hopefully this can get merged in soon.

**Comment by gfranko** [comment]
@purtuga Thanks for fixing this Paul!  Sorry it took so long =(

**Comment by purtuga** [comment]
No problem @gfranko ... Thanks for the awesome work.

**Pull request merged**
